name: komikplanet
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  showcaseview: ^3.0.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_database: ^11.0.0
  cloud_firestore: ^5.0.0
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  flutter_pdfview: ^1.3.2
  flutter_cached_pdfview: ^0.4.2
  path_provider: ^2.1.3
  firebase_storage: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/KomikPlanetLogo.png"
  min_sdk_android: 21 


flutter:
  assets:
   - assets/image/KomikPlanetLogo.png
   - assets/image/Komik1.png
   - assets/image/Komik2.png
   - assets/image/Cahapter1.png
   - assets/image/Tumbnail1.png
   - assets/image/Tumbnail2.png
   - assets/image/Tumbnail3.png
   - assets/image/Tumbnail4.png
   - assets/image/Tumbnail5.png
   - assets/image/Tumbnail6.png
   - assets/image/Tumbnail7.png
   - assets/image/Tumbnail8.png
   - assets/image/1.png
   - assets/image/2.png
   - assets/image/3.png
   - assets/image/4.png
   - assets/image/5.png
   - assets/image/6.png
   - assets/image/7.png
   - assets/image/8.png
   - assets/image/9.png
   - assets/image/10.png
   - assets/image/11.png
   - assets/image/12.png
   - assets/image/13.png
   - assets/image/14.png
   - assets/image/15.png
   - assets/image/16.png
   - assets/image/17.png
   - assets/image/18.png
   - assets/image/19.png
   - assets/image/20.png
   - assets/image/21.png
   - assets/image/22.png
   - assets/image/23.png
   - assets/image/24.png
   - assets/image/25.png
   - assets/image/26.png
   
   
   
  
   
   
   
   - assets/pdf/Chapter 1 tensei no isekai.pdf
   

  uses-material-design: true



  fonts:
    - family: comic
      fonts:
        - asset: assets/Fonts/comic.ttf
          weight: 700
